# Generated by Django 4.2.23 on 2025-07-18 16:48

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0002_cart_medicine_medicinegenre_order_produce_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='description',
            new_name='ingredient',
        ),
        migrations.RemoveField(
            model_name='medicinegenre',
            name='icon',
        ),
        migrations.AddField(
            model_name='medicine',
            name='benefit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='format',
            field=models.CharField(choices=[('hop', 'Hộp'), ('chai', 'Chai'), ('tuyp', 'Tuýp')], default='hop', max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicinegenre',
            name='imgMedicineGenreUrl',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='imgMedicineGenre'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='use',
            field=models.TextField(blank=True, null=True),
        ),
    ]
