# Generated by Django 4.2.23 on 2025-07-18 17:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0003_rename_description_medicine_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinegenre',
            name='imgMedicineGenreUrl',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
