# Generated by Django 4.2.23 on 2025-07-19 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0004_alter_medicinegenre_imgmedicinegenreurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='title',
            new_name='description',
        ),
    ]
