# Generated by Django 4.2.23 on 2025-07-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0006_alter_medicine_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='format',
            field=models.CharField(choices=[('hop', 'Hộp'), ('chai', 'Chai'), ('tuyp', 'Tuýp'), ('cai', 'Cái')], default='hop', max_length=20),
        ),
    ]
