# Generated by Django 4.2.23 on 2025-07-28 22:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0007_alter_medicine_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='ingredient',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='medicineimage',
            name='imgMedicineUrl',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
