# Generated by Django 4.2.23 on 2025-07-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0008_alter_medicine_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='ingredient',
            field=models.TextField(blank=True, null=True),
        ),
    ]
