# Generated by Django 4.2.23 on 2025-08-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0010_alter_order_status_chathistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatarUrl',
        ),
    ]
