# Generated by Django 4.2.23 on 2025-08-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0012_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
