# Generated by Django 4.2.23 on 2025-08-11 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0013_cartitem_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShippingMethod', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShippingFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('amount', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=255)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_detail', to='pharmacies.order')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineOrderShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('specific', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('online_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ship_info', to='pharmacies.onlineorder')),
            ],
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='online_order', to='pharmacies.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='pharmacies.shippingfee'),
        ),
    ]
