# Generated by Django 4.2.23 on 2025-08-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0014_onlineorder_shippingfee_remove_order_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineorder',
            name='ShippingMethod',
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='shipping_method',
            field=models.CharField(choices=[('home_delivery', 'Giao hàng tại nhà'), ('store_pickup', 'Nhận hàng tại cửa hàng')], default='store_pickup', max_length=20),
        ),
    ]
