# Generated by Django 4.2.23 on 2025-08-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0015_remove_onlineorder_shippingmethod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('waiting_for_pickup', 'Chờ lấy hàng'), ('waiting_for_delivery', 'Chờ giao hàng'), ('delivered', 'Đã giao'), ('canceled', 'Đã hủy')], default='pending', max_length=20),
        ),
    ]
