# Generated by Django 4.2.23 on 2025-08-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0016_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(choices=[('vnpay', 'Thanh toán qua VNPay'), ('cod', 'Thanh toán tiền mặt khi nhận hàng')], default='vnpay', max_length=20),
        ),
    ]
