# Generated by Django 4.2.23 on 2025-08-24 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0019_user_fcm_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fcm_token',
        ),
    ]
