# Generated by Django 4.2.23 on 2025-08-26 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0020_remove_user_fcm_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatHistory',
        ),
    ]
