# Generated by Django 4.2.23 on 2025-08-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0021_delete_chathistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userRole',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('customer', 'Customer'), ('cus_off', 'Customer_offline')], default='customer', max_length=20),
        ),
    ]
